name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: # Матрица для тестирования с разными версиями Python (опционально)
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run unit tests
        run: pytest # Или python -m unittest discover, если используете unittest
      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r . -n 5 -q # Сканируем текущую директорию рекурсивно, выводим только ошибки выше уровня 5 (средний) и краткий вывод